### ISSUE TITLE
Error on load pluguin on kong.conf file

### ISSUE THREAD

**Issue by prabagodelrio** [bjwschaap/kong-plugin-jwt-auth#1]
Hi!
I'm interested in being able to use this plugin, I've installed it correctly in my local
![imagen](https://user-images.githubusercontent.com/25517820/85844767-8e1c6800-b7a3-11ea-970c-8d3b4e847a1f.png)
 
And when I enable the use of this plugin in the kong.conf file 
![imagen](https://user-images.githubusercontent.com/25517820/85845098-0420cf00-b7a4-11ea-9a10-37585101742d.png)

When I restart the kong instance and I get the following error:

![imagen](https://user-images.githubusercontent.com/25517820/85845321-56fa8680-b7a4-11ea-9243-7fdce23e19d3.png)

I think the problem is that the name of the plugin I'm using in the plugin property of the kong.conf file is not the right one, what is the right one?

Thank you very much in advance!

Greetings

**Comment by prabago** [comment]
a
